email:
  sender: "1833299761@qq.com"
  server: "smtp.qq.com"
  port: 587
  password: "jcyiyshqazmqhaih"
  to_addr: "xmdjy703@outlook.com"

llm:
  api_keys: '80000cbc82d1476e9cbf31cd95a6aaee.vy5QOjzvOXRCapQI'

papaers:
  max_results: 50
  query_content: "cs.AI OR cs.CV OR cs.LG OR cs.RO OR cs.HC OR cs.NE"